### ISSUE TITLE
Prepare canonical TEI export

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-xml#42]
* [x] mapping table to get rid of most of `ge:` and `f:` elements and attributes
* [ ] look out for inconstencies
* [ ] add proper TEI headers
* [x] write schema with custom elements which are not transformed

**Comment by gerritbruening** [comment]
See also https://github.com/faustedition/faust-app/issues/33.

**Comment by gerritbruening** [comment]
[tei-mapping.xlsx](https://github.com/faustedition/xml/files/1040726/tei-mapping.xlsx)

@thvitt , here you find the mapping table.

**Comment by gerritbruening** [comment]
See also https://github.com/faustedition/faust-gen-html/issues/53.

**Comment by gerritbruening** [comment]
Problem is `mod rend="overwrite"`.

**Comment by thvitt** [comment]
I have now mainly finished both the ODD file adaption to the current TEI version and a conversion for the transcripts, including both the textual and diplomatic transcripts. [The corresponding build job](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/) contains both schema artefacts and a [validation report](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/Validation_20Results/). The converted version of the transcripts can be [retrieved from the job’s workspace](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/ws/target/converted/).

The next steps would involve:
- check the remaining validation errors whether they are errors in the code or require further adaptions in the schema (@gerritbruening @dietmarpravida @thvitt)
- adapt the edition’s source code for the renamed elements (@thvitt)
- check reading text and printed editions
- maybe further ODD cleanup steps?
- replace current sources with converted sources

**Comment by thvitt** [comment]
Consequences of the conversion in various other projects, illustrated using the mapping table:

Faust | TEI P5 v.2 | Problems | Used in dipl. Conversion | Used in CSS | Used in text. Conversion
-- | -- | -- | -- | -- | --
Elements |   |   |   |   |  
ge:stageNotes | listChange | #596 nesting | - |   | text-cleanup.xsl
ge:stageNote | change | #596 nesting | - |   | uri-map-json.xsl normalize-wsp.xsl
ge:document | sourceDoc | - | cfg |   | -
ge:surface | surface | - | cfg |   | -
ge:line | line | - | cfg⁰ |   | (issue188.xsl)
ge:transposeGrp | listTranspose | - | - |   | häufig
ge:transpose | transpose | - | - |   | häufig
ge:undo | undo | - | - |   | apparatus.xsl, textTranscr_transpose.xsl
ge:patch | surfaceGrp/surface type="patch" | surfaceGrp? | cfg, mit surface |   | -
ge:used | mod type="used" | ModSpan? #595 | cfg (???) |   | (issue188.xsl)
ge:rewrite | retrace | - | cfg | document-transcript | (issue188.xsl), text-cleanup.xsl
f:st[not(@rend="erase")] | mod rend="strikethrough" | - | cfg (???) |   | (issue188.xsl)
f:st[@rend="erase"] | mod rend="erase" | - | cfg (???) | .text.erase, .text-decoration-type-erase | (issue188.xsl)
f:overw | mod rend="overwrite" | - | cfg, strip! |   | -
f:under | seg rend="under" | - | cfg | document-transcript | -
f:over | seg rend="over" | - | cfg | document-transcript | -
f:hspace | space dim="horizontal" | - | cfg |   | -
f:vspace | space dim="vertical" | - | cfg |   | -
  |   |   |   |   |  
Attributes |   |   |   |   |  
ge:stage | change | - |   |   | häufig
alt/@targets | alt/@target | - |   |   | ja, mal suchen


* cfg = faust-transcript-configuration.js
* cfg⁰ = same, but shouldn’t need any change since namespace is ignored
* (???) = needs research

**Comment by gerritbruening** [comment]
My turn to do what?
Check column "Problems"?

**Comment by thvitt** [comment]
- review the [schema adjustments (ODD file)](https://github.com/faustedition/faust-schema/blob/tei-v340/src/main/odd/faust-tei.xml) whether you agree with those decisions
- review the [remaining validation issues](http://dev.digital-humanities.de/ci/view/Faust/job/faust-schema-tei-340/Validation_20Results/faust-tei.html). Decide whether they are source specific and can be dealt with manually or whether they are systematic and require some sot of action and if so, which (schema adjustment, automatic conversion …)
- decide what should be done with the TEI headers of diplomatic and textual transcripts and provide instructions when I should do something (like enter data from the metadata files)

**Comment by gerritbruening** [comment]
All remaining problems are dealt with in separate issues.
